version: '3.3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=passwdroot
      - MYSQL_DATABASE=overengineered
      - MYSQL_USER=tenxdev
      - MYSQL_PASSWORD=tenxpasswd
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - "./database/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/3.sql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u tenxdev --password=tenxpasswd
      interval: 5s
      timeout: 5s
      retries: 55
  webserver:
    image: webserver
    build:
      context: webserver
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://tenxdev:tenxpasswd@db:3306/overengineered
    networks:
      - backend
    ports:
      - 8080:8080
  kafka:
    image: bitnami/kafka:3.4.0
    environment:
      - BITNAMI_DEBUG=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
    networks:
      - backend
    ports:
      - 9094:9094


networks:
  frontend:
  backend: